#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

package:
  name: singa
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: https://github.com/apache/incubator-singa.git

build:
  number: 0
  string: py{{py}}_{{ environ.get('BUILD_STR', 'cpu') }}
  script_env:
    - CUDNN_PATH

requirements:
  build:
    - swig 3.0.10
    - openblas 0.2.19
    - protobuf 3.2.0
    - glog 0.3.4
    - libgfortran 3.0.0 # [osx]
    - gcc 4.8.5 # [linux]
    - python 2.7* [py27]
    - python 3.6* [py36]
    - numpy 1.12.0

  run:
    - openblas 0.2.19
    - protobuf 3.2.0
    - glog 0.3.4
    - libgfortran 3.0.0 # [osx]
    - libgcc 4.8.5 # [linux]
    - python 2.7* [py27]
    - python 3.6* [py36]
    - numpy >=1.12.0
    - flask >=0.10.1
    - flask-cors >=3.0.2
    - pillow >=2.3.0
    - future >=0.16.0

test:
  source_files:
    - test/python/*.py
  test:
    - python run.py

about:
  home: http://singa.apache.org/
  license: Apache V2
  license_file: LICENSE
  summary: SINGA is an Apache Incubating project for providing distributed deep learning. Apache disclaimers http://singa.apache.org/en/index.html#disclaimers
